#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import type { Command } from 'commander';
import { createProgram } from '../cli.js';

const OUTPUT_PATH = 'docs/reference/cli-help.md';
const HELP_WIDTH = 80;

function configureRecursively(command: Command): void {
  command.configureHelp({ helpWidth: HELP_WIDTH });
  for (const sub of command.commands) {
    configureRecursively(sub);
  }
}

function fullName(command: Command): string {
  const names: string[] = [];
  let current: Command | null = command;
  while (current) {
    names.unshift(current.name());
    current = current.parent ?? null;
  }
  return names.join(' ');
}

function anchor(command: Command): string {
  return fullName(command)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function renderToc(program: Command): string {
  const lines: string[] = ['## Commands', ''];
  function visit(command: Command, depth: number): void {
    const indent = '  '.repeat(depth);
    lines.push(`${indent}- [\`${fullName(command)}\`](#${anchor(command)})`);
    for (const sub of command.commands) {
      visit(sub, depth + 1);
    }
  }
  visit(program, 0);
  lines.push('');
  return lines.join('\n');
}

function renderCommand(command: Command, depth: number): string {
  const heading = '#'.repeat(depth);
  const help = command.helpInformation().trimEnd();
  const sections: string[] = [
    `${heading} \`${fullName(command)}\``,
    '',
    '```text',
    help,
    '```',
    '',
  ];
  for (const sub of command.commands) {
    sections.push(renderCommand(sub, depth + 1));
  }
  return sections.join('\n');
}

function render(program: Command): string {
  configureRecursively(program);

  const banner = [
    '<!-- DO NOT EDIT — generated by `npm run docs:cli-help` from packages/cli/src/cli.ts -->',
    '<!-- To regenerate: npm run docs:cli-help -->',
    '<!-- To verify drift: npm run check:docs:cli-help -->',
    '',
    `# ${program.name()} CLI help`,
    '',
    'Faithful projection of the Rundown CLI surface, generated from the running',
    'Commander program. For the user guide, see [cli.md](cli.md).',
    '',
  ].join('\n');

  const toc = renderToc(program);
  const body = renderCommand(program, 2);

  return `${banner}\n${toc}\n${body}`;
}

function firstDifference(committed: string, generated: string): string {
  const committedLines = committed.split('\n');
  const generatedLines = generated.split('\n');
  const max = Math.min(committedLines.length, generatedLines.length);
  for (let i = 0; i < max; i++) {
    if (committedLines[i] !== generatedLines[i]) {
      const lo = Math.max(0, i - 1);
      const hi = Math.min(max, i + 3);
      const out: string[] = [`First difference at line ${String(i + 1)}:`];
      for (let j = lo; j < hi; j++) {
        if (committedLines[j] !== generatedLines[j]) {
          out.push(`  - committed: ${JSON.stringify(committedLines[j] ?? '')}`);
          out.push(`  + generated: ${JSON.stringify(generatedLines[j] ?? '')}`);
        } else {
          out.push(`    ${JSON.stringify(committedLines[j])}`);
        }
      }
      return out.join('\n');
    }
  }
  if (committedLines.length !== generatedLines.length) {
    return `Files differ in length: committed=${String(committedLines.length)} lines, generated=${String(generatedLines.length)} lines`;
  }
  return 'Files differ but no specific line found (likely trailing whitespace)';
}

function printGeneratorHelp(): void {
  process.stdout.write(
    [
      'Usage: gen-cli-help [--check]',
      '',
      'Modes:',
      `  (default)  Regenerate ${OUTPUT_PATH}`,
      `  --check    Verify the committed file matches generator output; exit 1 on drift`,
      '',
    ].join('\n'),
  );
}

function main(): void {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) {
    printGeneratorHelp();
    return;
  }

  const program = createProgram();
  const generated = render(program);

  if (args.includes('--check')) {
    if (!existsSync(OUTPUT_PATH)) {
      process.stderr.write(`${OUTPUT_PATH} is missing — run \`npm run docs:cli-help\`\n`);
      process.exit(1);
    }
    const committed = readFileSync(OUTPUT_PATH, 'utf-8');
    if (committed === generated) {
      process.stdout.write(`${OUTPUT_PATH} is up to date\n`);
      return;
    }
    process.stderr.write(`${OUTPUT_PATH} is stale — run \`npm run docs:cli-help\`\n`);
    process.stderr.write(`${firstDifference(committed, generated)}\n`);
    process.exit(1);
  }

  writeFileSync(OUTPUT_PATH, generated);
  process.stdout.write(`wrote ${OUTPUT_PATH} (${String(generated.length)} bytes)\n`);
}

main();
